version: '4'
services:
  mysql:
    image: mysql:8.2.0
    container_name: inventory-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3317:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql